version: '3.5'

services:
  php:
    build:
      context: ./docker
    user: ddd-dev
    volumes:
    - .:/var/www/ddd-architectures-sandbox
    - ~/.composer:/home/ddd-dev/.composer

#  mysql:
#    image: mysql:8.0.21
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: ddd
#      TZ: 'Europe/Rome'
